build:
	./build.sh
start:
	docker-compose up
jupiter:
	open http://localhost:8888
master:
	open http://localhost:8080
worker1:
	open http://localhost:8081
master2:
	open http://localhost:8082
stop:
	docker-compose down
